"""Creating table of artifacts, param, artifact_params, init_db

Revision ID: 7352b3d70ab5
Revises: 
Create Date: 2025-03-10 18:12:40.450583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7352b3d70ab5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('en_name', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=1023), nullable=True),
    sa.Column('en_description', sa.String(length=1023), nullable=True),
    sa.Column('category', sa.String(length=63), nullable=False),
    sa.Column('en_category', sa.String(length=63), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stalcraft_project'
    )
    op.create_index(op.f('ix_stalcraft_project_artifacts_id'), 'artifacts', ['id'], unique=False, schema='stalcraft_project')
    op.create_table('params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('en_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stalcraft_project'
    )
    op.create_index(op.f('ix_stalcraft_project_params_id'), 'params', ['id'], unique=False, schema='stalcraft_project')
    op.create_table('artifact_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(length=15), nullable=True),
    sa.Column('param_id', sa.Integer(), nullable=True),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('name_color', sa.String(length=255), nullable=False),
    sa.Column('value_color', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['stalcraft_project.artifacts.id'], ),
    sa.ForeignKeyConstraint(['param_id'], ['stalcraft_project.params.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'param_id', name='_artifact_param_uc'),
    schema='stalcraft_project'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_params', schema='stalcraft_project')
    op.drop_index(op.f('ix_stalcraft_project_params_id'), table_name='params', schema='stalcraft_project')
    op.drop_table('params', schema='stalcraft_project')
    op.drop_index(op.f('ix_stalcraft_project_artifacts_id'), table_name='artifacts', schema='stalcraft_project')
    op.drop_table('artifacts', schema='stalcraft_project')
    # ### end Alembic commands ###
